/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => JournalPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// JournalView.ts
var import_obsidian2 = require("obsidian");

// utils.ts
var import_obsidian = require("obsidian");
function extractImagesFromContent(content, file, app) {
  var _a;
  const images = [];
  const wikiLinkRegex = /!\[\[([^\]]+)\]\]/g;
  let match;
  while ((match = wikiLinkRegex.exec(content)) !== null) {
    const imageRef = match[1];
    const position = match.index;
    const [imageName] = imageRef.split("|");
    const imageFile = app.metadataCache.getFirstLinkpathDest(
      imageName.trim(),
      file.path
    );
    if (imageFile && imageFile instanceof import_obsidian.TFile) {
      images.push({
        name: imageName.trim(),
        path: imageFile.path,
        url: app.vault.getResourcePath(imageFile),
        position
      });
    }
  }
  const markdownImageRegex = /!\[([^\]]*)\]\(([^)]+)\)/g;
  while ((match = markdownImageRegex.exec(content)) !== null) {
    const altText = match[1];
    const imagePath = match[2];
    const position = match.index;
    if (imagePath.startsWith("http://") || imagePath.startsWith("https://")) {
      continue;
    }
    let imageFile = null;
    if (imagePath.startsWith("/")) {
      imageFile = app.vault.getAbstractFileByPath(
        imagePath.slice(1)
      );
    } else {
      const fileDir = ((_a = file.parent) == null ? void 0 : _a.path) || "";
      const fullPath = fileDir ? `${fileDir}/${imagePath}` : imagePath;
      const normalizedPath = fullPath.split("/").filter((p) => p !== ".").join("/");
      imageFile = app.vault.getAbstractFileByPath(normalizedPath);
    }
    if (imageFile && imageFile instanceof import_obsidian.TFile) {
      images.push({
        name: imageFile.basename,
        path: imageFile.path,
        url: app.vault.getResourcePath(imageFile),
        altText: altText || void 0,
        position
      });
    }
  }
  return images.sort((a, b) => a.position - b.position);
}
function parseDateFromFileName(fileName) {
  const isoMatch = fileName.match(/(\d{4})-(\d{1,2})-(\d{1,2})/);
  if (isoMatch) {
    return new Date(
      parseInt(isoMatch[1]),
      parseInt(isoMatch[2]) - 1,
      parseInt(isoMatch[3])
    );
  }
  const chineseMatch = fileName.match(/(\d{4})年(\d{1,2})月(\d{1,2})日/);
  if (chineseMatch) {
    return new Date(
      parseInt(chineseMatch[1]),
      parseInt(chineseMatch[2]) - 1,
      parseInt(chineseMatch[3])
    );
  }
  const dotMatch = fileName.match(/(\d{4})\.(\d{1,2})\.(\d{1,2})/);
  if (dotMatch) {
    return new Date(
      parseInt(dotMatch[1]),
      parseInt(dotMatch[2]) - 1,
      parseInt(dotMatch[3])
    );
  }
  return null;
}
function parseDateFromContent(content) {
  const patterns = [
    /(\d{4})年(\d{1,2})月(\d{1,2})日/,
    // 2026年1月12日
    /(\d{4})-(\d{1,2})-(\d{1,2})/,
    // 2026-01-12
    /(\d{4})\/(\d{1,2})\/(\d{1,2})/
    // 2026/01/12
  ];
  for (const pattern of patterns) {
    const match = content.match(pattern);
    if (match) {
      return new Date(
        parseInt(match[1]),
        parseInt(match[2]) - 1,
        parseInt(match[3])
      );
    }
  }
  return null;
}
function parseDate(dateValue) {
  if (!dateValue)
    return null;
  if (dateValue instanceof Date) {
    return dateValue;
  }
  if (typeof dateValue === "string") {
    const parsed = new Date(dateValue);
    if (!isNaN(parsed.getTime())) {
      return parsed;
    }
  }
  return null;
}
function extractDate(file, content, app) {
  const fileNameDate = parseDateFromFileName(file.basename);
  if (fileNameDate)
    return fileNameDate;
  const metadata = app.metadataCache.getFileCache(file);
  if (metadata == null ? void 0 : metadata.frontmatter) {
    const dateFields = ["date", "Date", "created", "created_time"];
    for (const field of dateFields) {
      if (metadata.frontmatter[field]) {
        const parsed = parseDate(metadata.frontmatter[field]);
        if (parsed)
          return parsed;
      }
    }
  }
  const contentDate = parseDateFromContent(content);
  if (contentDate)
    return contentDate;
  return new Date(file.stat.ctime);
}
function extractTitle(content, fileName, app, file) {
  var _a;
  const metadata = app.metadataCache.getFileCache(file);
  if ((_a = metadata == null ? void 0 : metadata.frontmatter) == null ? void 0 : _a.title) {
    return metadata.frontmatter.title;
  }
  const h1Match = content.match(/^#\s+(.+)$/m);
  if (h1Match) {
    return h1Match[1].trim();
  }
  const h2Match = content.match(/^##\s+(.+)$/m);
  if (h2Match) {
    return h2Match[1].trim();
  }
  return fileName;
}
function generatePreview(content, maxLength) {
  const withoutFrontmatter = content.replace(/^---[\s\S]*?---\n/, "");
  const withoutImages = withoutFrontmatter.replace(
    /!\[\[[^\]]+\]\]|!\[[^\]]*\]\([^)]+\)/g,
    ""
  );
  const withoutHeaders = withoutImages.replace(/^#+\s+/gm, "");
  const text = withoutHeaders.replace(/[#*_`~\[\]()]/g, "").trim();
  if (text.length <= maxLength) {
    return text;
  }
  return text.substring(0, maxLength) + "...";
}
function countWords(content) {
  const withoutFrontmatter = content.replace(/^---[\s\S]*?---\n/, "");
  const text = withoutFrontmatter.replace(/[#*_`~\[\]()!]/g, "");
  const chineseChars = (text.match(/[\u4e00-\u9fa5]/g) || []).length;
  const englishWords = text.split(/\s+/).filter((w) => /[a-zA-Z]/.test(w)).length;
  return chineseChars + englishWords;
}
function formatDate(date) {
  const weekdays = [
    "\u661F\u671F\u65E5",
    "\u661F\u671F\u4E00",
    "\u661F\u671F\u4E8C",
    "\u661F\u671F\u4E09",
    "\u661F\u671F\u56DB",
    "\u661F\u671F\u4E94",
    "\u661F\u671F\u516D"
  ];
  return `${date.getFullYear()}\u5E74${date.getMonth() + 1}\u6708${date.getDate()}\u65E5 ${weekdays[date.getDay()]}`;
}
function groupByMonth(entries) {
  const grouped = {};
  for (const entry of entries) {
    const monthKey = `${entry.date.getFullYear()}\u5E74${entry.date.getMonth() + 1}\u6708`;
    if (!grouped[monthKey]) {
      grouped[monthKey] = [];
    }
    grouped[monthKey].push(entry);
  }
  return grouped;
}

// JournalView.ts
var JOURNAL_VIEW_TYPE = "journal-view";
var JournalView = class extends import_obsidian2.ItemView {
  // 目标文件夹路径
  constructor(leaf, app) {
    var _a;
    super(leaf);
    this.entries = [];
    this.isLoading = false;
    this.renderedEntries = /* @__PURE__ */ new Set();
    // 已渲染的条目索引
    this.itemsPerPage = 20;
    // 每页加载的条目数
    this.currentPage = 0;
    this.scrollContainer = null;
    this.loadMoreObserver = null;
    this.isLoadingMore = false;
    // 防止重复加载
    this.targetFolderPath = null;
    this.app = app;
    if (!this.contentEl && this.containerEl) {
      this.contentEl = this.containerEl.children[1];
    }
    if (!this.contentEl && this.containerEl) {
      this.contentEl = this.containerEl.createDiv("view-content");
    }
    console.log("[JournalView] \u6784\u9020\u51FD\u6570\u8C03\u7528");
    console.log("[JournalView] contentEl:", this.contentEl);
    console.log("[JournalView] containerEl:", this.containerEl);
    console.log("[JournalView] containerEl.children:", (_a = this.containerEl) == null ? void 0 : _a.children);
  }
  getViewType() {
    return JOURNAL_VIEW_TYPE;
  }
  getDisplayText() {
    return "\u624B\u8BB0\u89C6\u56FE";
  }
  getIcon() {
    return "calendar";
  }
  async onOpen() {
    var _a;
    console.log("[JournalView] onOpen \u88AB\u8C03\u7528");
    if (!this.contentEl && this.containerEl) {
      this.contentEl = this.containerEl.children[1];
    }
    if (!this.contentEl && this.containerEl) {
      this.contentEl = this.containerEl.createDiv("view-content");
    }
    console.log("[JournalView] onOpen - contentEl:", this.contentEl);
    console.log("[JournalView] onOpen - containerEl:", this.containerEl);
    console.log("[JournalView] onOpen - containerEl.children.length:", (_a = this.containerEl) == null ? void 0 : _a.children.length);
    if (!this.contentEl) {
      console.error("[JournalView] \u9519\u8BEF\uFF1A\u65E0\u6CD5\u627E\u5230 contentEl\uFF01");
      return;
    }
    this.renderEmpty();
  }
  // 显示空状态（等待用户手动触发扫描）- 应用 UI/UX Pro Max 设计原则
  renderEmpty() {
    if (!this.contentEl)
      return;
    this.contentEl.empty();
    this.contentEl.addClass("journal-view-container");
    this.contentEl.style.cssText = `
			padding: 0 !important;
			background: var(--background-primary) !important;
			color: var(--text-normal) !important;
			height: 100% !important;
			min-height: 100% !important;
			box-sizing: border-box !important;
			display: flex !important;
			flex-direction: column !important;
			overflow: hidden !important;
			position: relative !important;
		`;
    const welcomeEl = this.contentEl.createDiv("journal-welcome");
    welcomeEl.style.cssText = `
			display: flex;
			flex-direction: column;
			align-items: center;
			justify-content: center;
			height: 100%;
			padding: 60px 40px;
			text-align: center;
			max-width: 600px;
			margin: 0 auto;
			width: 100%;
		`;
    const cardEl = welcomeEl.createDiv("journal-welcome-card");
    cardEl.style.cssText = `
			background: var(--background-secondary);
			border-radius: 16px;
			padding: 48px 40px;
			width: 100%;
			box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
			border: 1px solid var(--background-modifier-border);
			transition: transform 0.2s ease, box-shadow 0.2s ease;
		`;
    const iconContainer = cardEl.createDiv("journal-welcome-icon-container");
    iconContainer.style.cssText = `
			width: 80px;
			height: 80px;
			border-radius: 20px;
			background: linear-gradient(135deg, var(--interactive-accent) 0%, var(--interactive-accent-hover) 100%);
			display: flex;
			align-items: center;
			justify-content: center;
			margin: 0 auto 24px;
			box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
		`;
    const iconSvg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    iconSvg.setAttribute("width", "40");
    iconSvg.setAttribute("height", "40");
    iconSvg.setAttribute("viewBox", "0 0 24 24");
    iconSvg.setAttribute("fill", "none");
    iconSvg.setAttribute("stroke", "currentColor");
    iconSvg.setAttribute("stroke-width", "2");
    iconSvg.setAttribute("stroke-linecap", "round");
    iconSvg.setAttribute("stroke-linejoin", "round");
    iconSvg.style.cssText = "color: var(--text-on-accent);";
    const path1 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path1.setAttribute("d", "M8 2v4");
    iconSvg.appendChild(path1);
    const path2 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path2.setAttribute("d", "M16 2v4");
    iconSvg.appendChild(path2);
    const rect = document.createElementNS("http://www.w3.org/2000/svg", "rect");
    rect.setAttribute("x", "3");
    rect.setAttribute("y", "4");
    rect.setAttribute("width", "18");
    rect.setAttribute("height", "18");
    rect.setAttribute("rx", "2");
    iconSvg.appendChild(rect);
    const path3 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path3.setAttribute("d", "M3 10h18");
    iconSvg.appendChild(path3);
    const path4 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path4.setAttribute("d", "M8 14h.01");
    iconSvg.appendChild(path4);
    const path5 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path5.setAttribute("d", "M12 14h.01");
    iconSvg.appendChild(path5);
    const path6 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path6.setAttribute("d", "M16 14h.01");
    iconSvg.appendChild(path6);
    const path7 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path7.setAttribute("d", "M8 18h.01");
    iconSvg.appendChild(path7);
    const path8 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path8.setAttribute("d", "M12 18h.01");
    iconSvg.appendChild(path8);
    const path9 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path9.setAttribute("d", "M16 18h.01");
    iconSvg.appendChild(path9);
    iconContainer.appendChild(iconSvg);
    const titleEl = cardEl.createEl("h2", { cls: "journal-welcome-title" });
    titleEl.textContent = "\u624B\u8BB0\u89C6\u56FE";
    titleEl.style.cssText = `
			font-size: 28px;
			font-weight: 600;
			margin: 0 0 12px 0;
			color: var(--text-normal);
			line-height: 1.3;
		`;
    const descEl = cardEl.createEl("p", { cls: "journal-welcome-desc" });
    descEl.textContent = "\u70B9\u51FB\u4E0B\u65B9\u6309\u94AE\u5F00\u59CB\u626B\u63CF\u548C\u52A0\u8F7D\u624B\u8BB0\u6761\u76EE";
    descEl.style.cssText = `
			font-size: 15px;
			color: var(--text-muted);
			margin: 0 0 32px 0;
			line-height: 1.6;
		`;
    const buttonEl = cardEl.createEl("button", { cls: "journal-start-button" });
    buttonEl.textContent = "\u5F00\u59CB\u626B\u63CF";
    buttonEl.setAttribute("aria-label", "\u5F00\u59CB\u626B\u63CF\u624B\u8BB0\u6761\u76EE");
    buttonEl.style.cssText = `
			padding: 14px 32px;
			font-size: 16px;
			font-weight: 500;
			background: var(--interactive-accent);
			color: var(--text-on-accent);
			border: none;
			border-radius: 10px;
			cursor: pointer;
			transition: all 0.2s ease;
			box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
			min-width: 140px;
			min-height: 44px;
			position: relative;
			overflow: hidden;
		`;
    buttonEl.addEventListener("focus", () => {
      buttonEl.style.outline = "2px solid var(--interactive-accent)";
      buttonEl.style.outlineOffset = "2px";
    });
    buttonEl.addEventListener("blur", () => {
      buttonEl.style.outline = "none";
    });
    buttonEl.addEventListener("mouseenter", () => {
      if (!buttonEl.disabled) {
        buttonEl.style.transform = "translateY(-1px)";
        buttonEl.style.boxShadow = "0 4px 8px rgba(0, 0, 0, 0.15)";
        buttonEl.style.background = "var(--interactive-accent-hover)";
      }
    });
    buttonEl.addEventListener("mouseleave", () => {
      if (!buttonEl.disabled) {
        buttonEl.style.transform = "translateY(0)";
        buttonEl.style.boxShadow = "0 2px 4px rgba(0, 0, 0, 0.1)";
        buttonEl.style.background = "var(--interactive-accent)";
      }
    });
    buttonEl.addEventListener("mousedown", () => {
      if (!buttonEl.disabled) {
        buttonEl.style.transform = "translateY(0)";
      }
    });
    buttonEl.addEventListener("click", async () => {
      buttonEl.disabled = true;
      buttonEl.style.opacity = "0.7";
      buttonEl.style.cursor = "not-allowed";
      buttonEl.textContent = "\u626B\u63CF\u4E2D...";
      this.contentEl.empty();
      await this.renderLoading();
      await new Promise((resolve) => setTimeout(resolve, 100));
      await this.loadEntries();
      await new Promise((resolve) => setTimeout(resolve, 50));
      this.render();
    });
  }
  // 渲染加载状态 - 使用骨架屏风格
  async renderLoading() {
    if (!this.contentEl)
      return;
    const loadingContainer = this.contentEl.createDiv("journal-loading-container");
    loadingContainer.style.cssText = `
			display: flex;
			flex-direction: column;
			align-items: center;
			justify-content: center;
			height: 100%;
			padding: 60px 40px;
		`;
    const spinner = loadingContainer.createDiv("journal-loading-spinner");
    spinner.style.cssText = `
			width: 48px;
			height: 48px;
			border: 4px solid var(--background-modifier-border);
			border-top-color: var(--interactive-accent);
			border-radius: 50%;
			animation: spin 0.8s linear infinite;
			margin-bottom: 24px;
		`;
    if (!document.getElementById("journal-spinner-style")) {
      const style = document.createElement("style");
      style.id = "journal-spinner-style";
      style.textContent = `
				@keyframes spin {
					to { transform: rotate(360deg); }
				}
			`;
      document.head.appendChild(style);
    }
    const loadingText = loadingContainer.createEl("p", { cls: "journal-loading-text" });
    loadingText.textContent = "\u6B63\u5728\u52A0\u8F7D\u624B\u8BB0\u89C6\u56FE...";
    loadingText.style.cssText = `
			font-size: 16px;
			color: var(--text-muted);
			margin: 0;
		`;
  }
  async onClose() {
    if (this.loadMoreObserver) {
      this.loadMoreObserver.disconnect();
      this.loadMoreObserver = null;
    }
    this.renderedEntries.clear();
  }
  async loadEntries() {
    if (this.isLoading)
      return;
    this.isLoading = true;
    try {
      let files = [];
      if (this.targetFolderPath) {
        const targetFolder = this.app.vault.getAbstractFileByPath(this.targetFolderPath);
        if (targetFolder instanceof import_obsidian2.TFolder) {
          files = this.getMarkdownFilesInFolder(targetFolder);
          console.log(`[JournalView] \u626B\u63CF\u6587\u4EF6\u5939 ${this.targetFolderPath}\uFF0C\u627E\u5230 ${files.length} \u4E2A Markdown \u6587\u4EF6`);
        } else {
          console.log(`[JournalView] \u6587\u4EF6\u5939 ${this.targetFolderPath} \u4E0D\u5B58\u5728\uFF0C\u626B\u63CF\u6574\u4E2A vault`);
          files = this.app.vault.getMarkdownFiles();
        }
      } else {
        files = this.app.vault.getMarkdownFiles();
        console.log(`[JournalView] \u627E\u5230 ${files.length} \u4E2A Markdown \u6587\u4EF6`);
      }
      this.entries = [];
      this.renderedEntries.clear();
      this.currentPage = 0;
      const entryPromises = [];
      for (const file of files) {
        entryPromises.push(
          this.loadEntryMetadata(file).catch((error) => {
            console.error(`[JournalView] \u5904\u7406\u6587\u4EF6 ${file.path} \u65F6\u51FA\u9519:`, error);
            return null;
          })
        );
      }
      const batchSize = 10;
      for (let i = 0; i < entryPromises.length; i += batchSize) {
        const batch = entryPromises.slice(i, i + batchSize);
        const results = await Promise.all(batch);
        this.entries.push(...results.filter((e) => e !== null));
        if (i % 50 === 0) {
          console.log(`[JournalView] \u5DF2\u5904\u7406 ${Math.min(i + batchSize, files.length)}/${files.length} \u4E2A\u6587\u4EF6`);
        }
      }
      this.entries.sort(
        (a, b) => b.date.getTime() - a.date.getTime()
      );
      console.log(`[JournalView] \u6210\u529F\u52A0\u8F7D ${this.entries.length} \u4E2A\u624B\u8BB0\u6761\u76EE\uFF08\u5143\u6570\u636E\uFF09`);
    } catch (error) {
      console.error("[JournalView] \u52A0\u8F7D\u6761\u76EE\u65F6\u51FA\u9519:", error);
    } finally {
      this.isLoading = false;
    }
  }
  // 只加载元数据，不加载完整内容（使用 Obsidian Metadata Cache 优化）
  async loadEntryMetadata(file) {
    var _a, _b;
    const metadata = this.app.metadataCache.getFileCache(file);
    if ((_a = metadata == null ? void 0 : metadata.frontmatter) == null ? void 0 : _a.date) {
      const frontmatterDate = parseDate(metadata.frontmatter.date);
      if (frontmatterDate) {
        return this.loadEntryMetadataFromCache(file, metadata, frontmatterDate);
      }
    }
    let content;
    try {
      const cachedContent = this.app.metadataCache.getFileCache(file);
      if (cachedContent && cachedContent.content) {
        content = cachedContent.content;
      } else {
        const fullContent = await this.app.vault.read(file);
        content = fullContent.substring(0, 2e3);
      }
    } catch (error) {
      console.error(`[JournalView] \u8BFB\u53D6\u6587\u4EF6\u5931\u8D25 ${file.path}:`, error);
      return null;
    }
    const date = extractDate(file, content, this.app);
    if (!date) {
      return null;
    }
    let images = [];
    if (metadata == null ? void 0 : metadata.embeds) {
      images = this.extractImagesFromMetadata(metadata, file);
    }
    if (images.length === 0) {
      const fullContent = await this.app.vault.read(file);
      images = extractImagesFromContent(fullContent, file, this.app);
      content = fullContent;
    }
    const wordCount = countWords(content);
    let title = ((_b = metadata == null ? void 0 : metadata.frontmatter) == null ? void 0 : _b.title) || "";
    if (!title) {
      title = extractTitle(content, file.basename, this.app, file);
    }
    const preview = generatePreview(content, 200);
    return {
      file,
      date,
      images,
      content: "",
      // 不保存完整内容，需要时再加载
      preview,
      wordCount,
      title
    };
  }
  // 从 metadata cache 快速加载（当 frontmatter 有日期时）
  // 这是最快的路径，不需要读取文件内容
  loadEntryMetadataFromCache(file, metadata, date) {
    var _a, _b, _c;
    const images = this.extractImagesFromMetadata(metadata, file);
    const title = ((_a = metadata.frontmatter) == null ? void 0 : _a.title) || file.basename;
    let preview = "";
    if ((_b = metadata.frontmatter) == null ? void 0 : _b.description) {
      preview = metadata.frontmatter.description;
    } else if (metadata.headings && metadata.headings.length > 0) {
      preview = metadata.headings[0].heading;
    } else {
      preview = title;
    }
    const wordCount = ((_c = metadata.frontmatter) == null ? void 0 : _c.wordCount) || 0;
    return {
      file,
      date,
      images,
      content: "",
      preview: preview || "\u65E0\u9884\u89C8",
      wordCount,
      title
    };
  }
  // 从 metadata cache 提取图片
  extractImagesFromMetadata(metadata, file) {
    var _a, _b;
    const images = [];
    if (metadata.embeds) {
      for (const embed of metadata.embeds) {
        const imageFile = this.app.metadataCache.getFirstLinkpathDest(
          embed.link,
          file.path
        );
        if (imageFile && imageFile instanceof import_obsidian2.TFile) {
          const ext = imageFile.extension.toLowerCase();
          if (["png", "jpg", "jpeg", "gif", "webp", "svg", "bmp"].includes(ext)) {
            images.push({
              name: embed.link,
              path: imageFile.path,
              url: this.app.vault.getResourcePath(imageFile),
              altText: embed.displayText || "",
              position: ((_b = (_a = embed.position) == null ? void 0 : _a.start) == null ? void 0 : _b.line) || 0
            });
          }
        }
      }
    }
    return images;
  }
  // 按需加载完整内容
  async loadEntryContent(entry) {
    if (entry.content)
      return;
    try {
      entry.content = await this.app.vault.read(entry.file);
    } catch (error) {
      console.error(`[JournalView] \u52A0\u8F7D\u6587\u4EF6\u5185\u5BB9\u5931\u8D25 ${entry.file.path}:`, error);
    }
  }
  render() {
    let container = this.contentEl;
    if (!container && this.containerEl) {
      container = this.containerEl.children[1];
    }
    if (!container && this.containerEl) {
      container = this.containerEl.querySelector(".view-content");
    }
    if (!container && this.containerEl) {
      container = this.containerEl.createDiv("view-content");
      this.contentEl = container;
    }
    if (!container) {
      console.error("[JournalView] \u9519\u8BEF\uFF1A\u65E0\u6CD5\u627E\u5230\u6216\u521B\u5EFA\u5BB9\u5668\uFF01");
      console.error("[JournalView] containerEl:", this.containerEl);
      return;
    }
    console.log("[JournalView] \u4F7F\u7528\u5BB9\u5668:", container);
    this.renderToContainer(container);
  }
  renderToContainer(container) {
    container.empty();
    container.addClass("journal-view-container");
    container.style.cssText = `
			padding: 20px !important;
			background: var(--background-primary) !important;
			color: var(--text-normal) !important;
			height: 100% !important;
			min-height: 100% !important;
			box-sizing: border-box !important;
			display: flex !important;
			flex-direction: column !important;
			overflow: hidden !important;
			position: relative !important;
		`;
    if (this.isLoading) {
      const loadingEl = container.createDiv({
        text: "\u52A0\u8F7D\u4E2D...",
        cls: "journal-loading"
      });
      loadingEl.style.cssText = "text-align: center; padding: 40px; color: var(--text-normal);";
      console.log("[JournalView] \u663E\u793A\u52A0\u8F7D\u4E2D");
      return;
    }
    if (this.entries.length === 0) {
      const emptyEl = container.createDiv({
        text: "\u6CA1\u6709\u627E\u5230\u624B\u8BB0\u6761\u76EE\u3002\u8BF7\u786E\u4FDD\u6587\u4EF6\u5305\u542B\u65E5\u671F\u4FE1\u606F\uFF08\u6587\u4EF6\u540D\u3001frontmatter \u6216\u6B63\u6587\uFF09\u3002\n\n\u63D0\u793A\uFF1A\n- \u6587\u4EF6\u540D\u683C\u5F0F\uFF1A2026-01-12.md \u6216 2026\u5E741\u670812\u65E5.md\n- Frontmatter\uFF1Adate: 2026-01-12\n- \u6B63\u6587\u5185\u5BB9\uFF1A2026\u5E741\u670812\u65E5",
        cls: "journal-empty"
      });
      emptyEl.style.cssText = "text-align: center; padding: 40px; color: var(--text-normal); white-space: pre-line;";
      console.log("[JournalView] \u6CA1\u6709\u627E\u5230\u6761\u76EE");
      return;
    }
    console.log(`[JournalView] \u5F00\u59CB\u6E32\u67D3 ${this.entries.length} \u4E2A\u6761\u76EE\uFF08\u4F7F\u7528\u5206\u9875\u52A0\u8F7D\uFF09`);
    this.renderStats(container);
    console.log("[JournalView] \u7EDF\u8BA1\u4FE1\u606F\u5DF2\u6E32\u67D3");
    const statsEl = container.querySelector(".journal-stats");
    if (statsEl) {
      statsEl.style.cssText = `
				display: flex !important;
				gap: 20px !important;
				margin-bottom: 30px !important;
				padding: 20px !important;
				background: var(--background-secondary) !important;
				border-radius: 12px !important;
				flex-wrap: wrap !important;
				position: relative !important;
				z-index: 2 !important;
			`;
    }
    this.scrollContainer = container.createDiv("journal-scroll-container");
    this.scrollContainer.style.cssText = `
			overflow-y: auto !important;
			overflow-x: hidden !important;
			flex: 1 1 0% !important;
			min-height: 0 !important;
			display: block !important;
			background: transparent !important;
			width: 100% !important;
			position: relative !important;
			-webkit-overflow-scrolling: touch !important;
			z-index: 1 !important;
		`;
    console.log("[JournalView] \u521B\u5EFA\u6EDA\u52A8\u5BB9\u5668:", this.scrollContainer);
    console.log("[JournalView] \u6EDA\u52A8\u5BB9\u5668\u7236\u5143\u7D20:", this.scrollContainer.parentElement);
    this.renderListPaginated(this.scrollContainer);
    this.setupLazyLoading(this.scrollContainer);
  }
  setupLazyLoading(container) {
    if (this.loadMoreObserver) {
      this.loadMoreObserver.disconnect();
      this.loadMoreObserver = null;
    }
    this.loadMoreObserver = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting && !this.isLoadingMore) {
            setTimeout(() => {
              if (!this.isLoadingMore) {
                this.loadMoreEntries(container);
              }
            }, 100);
          }
        });
      },
      {
        root: container,
        rootMargin: "100px",
        // 减少提前加载距离
        threshold: 0.1
        // 至少10%可见才触发
      }
    );
    setTimeout(() => {
      var _a;
      const loadMoreTrigger = container.querySelector(".journal-load-more-trigger");
      if (loadMoreTrigger) {
        (_a = this.loadMoreObserver) == null ? void 0 : _a.observe(loadMoreTrigger);
      }
    }, 200);
  }
  async loadMoreEntries(container) {
    var _a, _b, _c;
    if (this.isLoadingMore) {
      console.log("[JournalView] \u6B63\u5728\u52A0\u8F7D\u4E2D\uFF0C\u8DF3\u8FC7\u91CD\u590D\u8BF7\u6C42");
      return;
    }
    const startIndex = this.currentPage * this.itemsPerPage;
    const endIndex = Math.min(startIndex + this.itemsPerPage, this.entries.length);
    if (startIndex >= this.entries.length) {
      console.log("[JournalView] \u6CA1\u6709\u66F4\u591A\u5185\u5BB9\u4E86");
      const trigger = container.querySelector(".journal-load-more-trigger");
      if (trigger) {
        (_a = this.loadMoreObserver) == null ? void 0 : _a.unobserve(trigger);
        trigger.remove();
      }
      return;
    }
    this.isLoadingMore = true;
    console.log(`[JournalView] loadMoreEntries: ${startIndex} - ${endIndex} (\u5171 ${this.entries.length} \u4E2A)`);
    try {
      const oldTrigger = container.querySelector(".journal-load-more-trigger");
      if (oldTrigger) {
        (_b = this.loadMoreObserver) == null ? void 0 : _b.unobserve(oldTrigger);
        oldTrigger.remove();
      }
      await this.renderEntriesBatch(container, startIndex, endIndex);
      console.log(`[JournalView] \u5DF2\u6E32\u67D3 ${endIndex - startIndex} \u4E2A\u6761\u76EE`);
      if (endIndex < this.entries.length) {
        const trigger = container.createDiv("journal-load-more-trigger");
        trigger.style.cssText = `
					height: 1px !important;
					margin: 20px 0 !important;
					visibility: hidden !important;
					opacity: 0 !important;
					pointer-events: none !important;
					position: absolute !important;
					width: 1px !important;
				`;
        (_c = this.loadMoreObserver) == null ? void 0 : _c.observe(trigger);
      }
      this.currentPage++;
    } finally {
      this.isLoadingMore = false;
    }
  }
  async renderEntriesBatch(container, startIndex, endIndex) {
    const batchEntries = this.entries.slice(startIndex, endIndex);
    const grouped = groupByMonth(batchEntries);
    console.log(`[JournalView] renderEntriesBatch: \u5904\u7406 ${batchEntries.length} \u4E2A\u6761\u76EE\uFF0C\u5206\u4E3A ${Object.keys(grouped).length} \u4E2A\u6708\u4EFD`);
    const sortedMonths = Object.keys(grouped).sort((a, b) => {
      const dateA = this.parseMonthKey(a);
      const dateB = this.parseMonthKey(b);
      return dateB.getTime() - dateA.getTime();
    });
    for (const monthKey of sortedMonths) {
      const entries = grouped[monthKey];
      let monthSection = container.querySelector(
        `.journal-month-section[data-month="${monthKey}"]`
      );
      if (!monthSection) {
        monthSection = container.createDiv("journal-month-section");
        monthSection.setAttribute("data-month", monthKey);
        const title = monthSection.createEl("h2", {
          text: monthKey,
          cls: "journal-month-title"
        });
        console.log(`[JournalView] \u521B\u5EFA\u6708\u4EFD\u6807\u9898: ${monthKey}`);
      }
      for (const entry of entries) {
        const entryIndex = this.entries.indexOf(entry);
        if (!this.renderedEntries.has(entryIndex)) {
          const card = await this.createJournalCard(entry);
          monthSection.appendChild(card);
          this.renderedEntries.add(entryIndex);
        }
      }
    }
    console.log(`[JournalView] renderEntriesBatch \u5B8C\u6210\uFF0C\u5BB9\u5668\u5B50\u5143\u7D20\u6570: ${container.children.length}`);
  }
  renderStats(container) {
    const statsEl = container.createDiv("journal-stats");
    const totalEntries = this.entries.length;
    const totalWords = this.entries.reduce((sum, e) => sum + e.wordCount, 0);
    const totalImages = this.entries.reduce((sum, e) => sum + e.images.length, 0);
    const consecutiveDays = this.calculateConsecutiveDays();
    const stat1 = statsEl.createDiv("journal-stat-item");
    stat1.innerHTML = `<span class="journal-stat-icon">\u{1F525}</span><span class="journal-stat-value">${consecutiveDays}</span><span class="journal-stat-label">\u8FDE\u7EED\u7EAA\u5F55\u5929\u6570</span>`;
    const stat2 = statsEl.createDiv("journal-stat-item");
    stat2.innerHTML = `<span class="journal-stat-icon">\u{1F4AC}</span><span class="journal-stat-value">${totalWords.toLocaleString()}</span><span class="journal-stat-label">\u5B57\u6570</span>`;
    const stat3 = statsEl.createDiv("journal-stat-item");
    stat3.innerHTML = `<span class="journal-stat-icon">\u{1F4C5}</span><span class="journal-stat-value">${totalEntries}</span><span class="journal-stat-label">\u5199\u624B\u8BB0\u5929\u6570</span>`;
  }
  calculateConsecutiveDays() {
    if (this.entries.length === 0)
      return 0;
    const dates = new Set(
      this.entries.map((e) => {
        const d = new Date(e.date);
        d.setHours(0, 0, 0, 0);
        return d.getTime();
      })
    );
    const sortedDates = Array.from(dates).sort((a, b) => b - a);
    if (sortedDates.length === 0)
      return 0;
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const todayTime = today.getTime();
    let consecutive = 0;
    let currentDate = todayTime;
    for (const dateTime of sortedDates) {
      if (dateTime === currentDate) {
        consecutive++;
        currentDate -= 24 * 60 * 60 * 1e3;
      } else if (dateTime < currentDate) {
        break;
      }
    }
    return consecutive;
  }
  renderListPaginated(container) {
    this.currentPage = 0;
    this.renderedEntries.clear();
    this.isLoadingMore = false;
    container.empty();
    container.style.background = "transparent";
    console.log("[JournalView] renderListPaginated \u88AB\u8C03\u7528");
    console.log(`[JournalView] \u603B\u6761\u76EE\u6570: ${this.entries.length}, \u6BCF\u9875: ${this.itemsPerPage}`);
    this.loadMoreEntries(container).catch((error) => {
      console.error("[JournalView] loadMoreEntries \u51FA\u9519:", error);
      this.isLoadingMore = false;
    });
  }
  parseMonthKey(monthKey) {
    const match = monthKey.match(/(\d{4})年(\d{1,2})月/);
    if (match) {
      return new Date(parseInt(match[1]), parseInt(match[2]) - 1, 1);
    }
    return new Date();
  }
  async createJournalCard(entry) {
    const card = document.createElement("div");
    card.addClass("journal-card");
    const dateEl = card.createDiv("journal-date");
    dateEl.textContent = formatDate(entry.date);
    if (entry.title) {
      const titleEl = card.createEl("h3", { cls: "journal-title" });
      titleEl.textContent = entry.title;
    }
    if (entry.images.length > 0) {
      const imagesEl = card.createDiv("journal-images");
      const displayImages = entry.images.slice(0, 3);
      for (const image of displayImages) {
        const imgContainer = imagesEl.createDiv("journal-image-container");
        const img = document.createElement("img");
        img.alt = image.altText || image.name;
        img.addClass("journal-image");
        img.loading = "lazy";
        img.decoding = "async";
        const imageObserver = new IntersectionObserver((entries) => {
          entries.forEach((entry2) => {
            if (entry2.isIntersecting) {
              img.src = image.url;
              imageObserver.unobserve(img);
            }
          });
        }, { rootMargin: "50px" });
        imageObserver.observe(img);
        imgContainer.appendChild(img);
      }
      if (entry.images.length > 3) {
        const lastImageContainer = imagesEl.children[imagesEl.children.length - 1];
        if (lastImageContainer) {
          const moreEl = lastImageContainer.createDiv("journal-image-more");
          moreEl.textContent = `+${entry.images.length - 3}`;
          moreEl.style.cssText = `
						position: absolute !important;
						top: 0 !important;
						left: 0 !important;
						right: 0 !important;
						bottom: 0 !important;
						display: flex !important;
						align-items: center !important;
						justify-content: center !important;
						background: rgba(0, 0, 0, 0.6) !important;
						color: white !important;
						font-size: 24px !important;
						font-weight: 600 !important;
						pointer-events: none !important;
						z-index: 10 !important;
					`;
        }
      }
    }
    const contentEl = card.createDiv("journal-content");
    const previewEl = contentEl.createDiv("journal-preview");
    previewEl.textContent = entry.preview;
    const metaEl = card.createDiv("journal-meta");
    metaEl.createSpan({
      text: `\u5B57\u6570: ${entry.wordCount}`,
      cls: "journal-meta-item"
    });
    if (entry.images.length > 0) {
      metaEl.createSpan({
        text: `\u56FE\u7247: ${entry.images.length}`,
        cls: "journal-meta-item"
      });
    }
    card.addEventListener("click", (e) => {
      if (e.target === card || card.contains(e.target)) {
        if (this.scrollContainer) {
          const isScrolling = this.scrollContainer.scrollTop !== this.scrollContainer._lastScrollTop;
          this.scrollContainer._lastScrollTop = this.scrollContainer.scrollTop;
          if (isScrolling) {
            return;
          }
        }
        this.app.workspace.openLinkText(entry.file.path, "", true);
      }
    });
    card.setAttribute("data-file-path", entry.file.path);
    card.style.cursor = "pointer";
    card.style.userSelect = "none";
    return card;
  }
  async refresh() {
    await this.loadEntries();
    this.render();
  }
  // 递归获取文件夹下的所有 Markdown 文件
  getMarkdownFilesInFolder(folder) {
    const files = [];
    for (const child of folder.children) {
      if (child instanceof import_obsidian2.TFile && child.extension === "md") {
        if (!child.basename.startsWith(".") && child.basename !== "\u624B\u8BB0\u89C6\u56FE") {
          files.push(child);
        }
      } else if (child instanceof import_obsidian2.TFolder) {
        files.push(...this.getMarkdownFilesInFolder(child));
      }
    }
    return files;
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  folderPath: "",
  imageLimit: 3,
  folderJournalViews: {}
};
var JournalPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.view = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(JOURNAL_VIEW_TYPE, (leaf) => {
      const view = new JournalView(leaf, this.app);
      this.view = view;
      return view;
    });
    this.addCommand({
      id: "open-journal-view",
      name: "\u6253\u5F00\u624B\u8BB0\u89C6\u56FE",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "refresh-journal-view",
      name: "\u5237\u65B0\u624B\u8BB0\u89C6\u56FE",
      callback: () => {
        if (this.view) {
          this.view.refresh();
        }
      }
    });
    this.addSettingTab(new JournalSettingTab(this.app, this));
    this.registerFolderContextMenu();
    this.registerDomEvent(document, "click", (evt) => {
      this.handleFileExplorerClick(evt);
    }, true);
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        this.handleFileOpen(file);
      })
    );
    this.app.workspace.onLayoutReady(() => {
      const existingLeaf = this.app.workspace.getLeavesOfType(
        JOURNAL_VIEW_TYPE
      )[0];
      if (existingLeaf && existingLeaf.view instanceof JournalView) {
        this.view = existingLeaf.view;
      }
    });
  }
  registerFolderContextMenu() {
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian3.TFolder) {
          menu.addItem((item) => {
            item.setTitle("\u624B\u8BB0").setIcon("calendar");
            const submenu = item.setSubmenu();
            submenu.addItem((subItem) => {
              subItem.setTitle("\u521B\u5EFA\u6587\u4EF6\u5939\u624B\u8BB0\u89C6\u56FE").setIcon("link").onClick(async () => {
                await this.createFolderJournalView(file);
              });
            });
            submenu.addItem((subItem) => {
              subItem.setTitle("\u521B\u5EFA\u5B50\u6587\u4EF6\u624B\u8BB0\u89C6\u56FE").setIcon("file-plus").onClick(async () => {
                await this.createSubFileJournalView(file);
              });
            });
          });
        }
      })
    );
  }
  async createFolderJournalView(folder) {
    this.settings.folderJournalViews[folder.path] = folder.path;
    await this.saveSettings();
    new import_obsidian3.Notice(`\u5DF2\u4E3A\u6587\u4EF6\u5939 "${folder.name}" \u521B\u5EFA\u624B\u8BB0\u89C6\u56FE\u5173\u8054\u3002\u70B9\u51FB\u6587\u4EF6\u5939\u65F6\u5C06\u81EA\u52A8\u6253\u5F00\u624B\u8BB0\u89C6\u56FE\u3002`);
    await this.openFolderJournalView(folder);
  }
  async createSubFileJournalView(folder) {
    const viewFileName = `${folder.name}\u624B\u8BB0\u89C6\u56FE.md`;
    const viewPath = `${folder.path}/${viewFileName}`;
    const viewContent = `---
journal-view: true
folder-path: ${folder.path}
type: sub-file
---

# ${folder.name} \u624B\u8BB0\u89C6\u56FE

\u6B64\u6587\u4EF6\u663E\u793A\u6587\u4EF6\u5939 "${folder.name}" \u4E0B\u7684\u6240\u6709\u624B\u8BB0\u6761\u76EE\u3002

## \u4F7F\u7528\u8BF4\u660E

- \u6B64\u6587\u4EF6\u4F1A\u81EA\u52A8\u626B\u63CF\u5F53\u524D\u6587\u4EF6\u5939\u4E0B\u7684\u6240\u6709 Markdown \u6587\u4EF6
- \u6309\u65E5\u671F\u7EC4\u7EC7\u663E\u793A
- \u652F\u6301\u56FE\u7247\u9884\u89C8\u548C\u5185\u5BB9\u9884\u89C8
`;
    try {
      const existingFile = this.app.vault.getAbstractFileByPath(viewPath);
      if (existingFile instanceof import_obsidian3.TFile) {
        new import_obsidian3.Notice(`\u6587\u4EF6 "${viewFileName}" \u5DF2\u5B58\u5728`);
        await this.openFolderJournalView(folder);
      } else {
        await this.app.vault.create(viewPath, viewContent);
        await this.openFolderJournalView(folder);
        new import_obsidian3.Notice(`\u5DF2\u521B\u5EFA\u624B\u8BB0\u89C6\u56FE\u6587\u4EF6: ${viewFileName}`);
      }
    } catch (error) {
      console.error("[JournalView] \u521B\u5EFA\u5B50\u6587\u4EF6\u624B\u8BB0\u89C6\u56FE\u5931\u8D25:", error);
      new import_obsidian3.Notice(`\u521B\u5EFA\u5931\u8D25: ${error.message}`);
    }
  }
  handleFileExplorerClick(evt) {
    const target = evt.target;
    if (!(target instanceof HTMLElement))
      return;
    const folderTitleEl = target.closest(".nav-folder-title");
    if (!folderTitleEl)
      return;
    const folderPath = folderTitleEl.getAttribute("data-path");
    if (!folderPath)
      return;
    const viewPath = this.settings.folderJournalViews[folderPath];
    if (viewPath) {
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (folder instanceof import_obsidian3.TFolder) {
        evt.preventDefault();
        evt.stopImmediatePropagation();
        this.openFolderJournalView(folder);
      }
    }
  }
  async handleFileOpen(file) {
    var _a;
    if (!file)
      return;
    if (file.basename.endsWith("\u624B\u8BB0\u89C6\u56FE")) {
      const metadata = this.app.metadataCache.getFileCache(file);
      if ((_a = metadata == null ? void 0 : metadata.frontmatter) == null ? void 0 : _a["journal-view"]) {
        const folderPath = metadata.frontmatter["folder-path"];
        if (folderPath) {
          const folder = this.app.vault.getAbstractFileByPath(folderPath);
          if (folder instanceof import_obsidian3.TFolder) {
            setTimeout(async () => {
              await this.openFolderJournalView(folder);
            }, 100);
          }
        }
      }
    }
  }
  async openFolderJournalView(folder) {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(JOURNAL_VIEW_TYPE)[0];
    if (!leaf) {
      const newLeaf = workspace.getLeaf(true);
      if (newLeaf) {
        await newLeaf.setViewState({ type: JOURNAL_VIEW_TYPE, active: true });
        leaf = newLeaf;
      }
    }
    if (leaf && leaf.view instanceof JournalView) {
      leaf.view.targetFolderPath = folder.path;
      await leaf.view.refresh();
      workspace.revealLeaf(leaf);
    }
  }
  async onunload() {
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(JOURNAL_VIEW_TYPE)[0];
    if (!leaf) {
      const newLeaf = workspace.getLeaf(true);
      if (newLeaf) {
        await newLeaf.setViewState({ type: JOURNAL_VIEW_TYPE, active: true });
        leaf = newLeaf;
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var JournalSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u624B\u8BB0\u89C6\u56FE\u8BBE\u7F6E" });
    new import_obsidian3.Setting(containerEl).setName("\u6587\u4EF6\u5939\u8DEF\u5F84").setDesc("\u8981\u626B\u63CF\u7684\u6587\u4EF6\u5939\u8DEF\u5F84\uFF08\u7559\u7A7A\u5219\u626B\u63CF\u6574\u4E2A vault\uFF09").addText(
      (text) => text.setPlaceholder("\u4F8B\u5982: \u65E5\u8BB0/").setValue(this.plugin.settings.folderPath).onChange(async (value) => {
        this.plugin.settings.folderPath = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u56FE\u7247\u663E\u793A\u9650\u5236").setDesc("\u6BCF\u4E2A\u624B\u8BB0\u5361\u7247\u6700\u591A\u663E\u793A\u7684\u56FE\u7247\u6570\u91CF").addSlider(
      (slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.imageLimit).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.imageLimit = value;
        await this.plugin.saveSettings();
        if (this.plugin.view) {
          this.plugin.view.refresh();
        }
      })
    );
  }
};
